# Generated by Django 2.2 on 2020-08-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.CharField(choices=[('bad', 'Bad'), ('bverage', 'Average'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20)),
                ('recommened', models.CharField(choices=[('very_likely', 'Very Likely'), ('likely', 'Likely'), ('not_recommend', 'Not Recommend')], max_length=20)),
                ('msg', models.TextField(max_length=400)),
            ],
        ),
    ]
