# Generated by Django 2.2 on 2020-08-07 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('n', 'Not Specified'), ('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='Not Specified', max_length=6)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile')),
                ('bio', models.TextField()),
            ],
        ),
    ]
