# Generated by Django 2.2 on 2020-08-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='slug',
            field=models.SlugField(default='pro', unique=True),
            preserve_default=False,
        ),
    ]
