# Generated by Django 2.2 on 2020-08-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_user_detail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='dob',
            field=models.DateField(auto_now_add=True),
        ),
    ]
